name: GCToolKit build with Maven

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'    
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'microsoft'
        cache: 'maven'
        
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml 
